### ISSUE TITLE
Transition to 5.0.1 - "Value cannot be null" in CreateInlineSchema

### ISSUE THREAD

**Issue by latenightcoder** [domaindrivendev/Swashbuckle#213]
Hi,

In an attempt to fix the generic arguments issue in Swashbuckle 4.0, I just upgraded to 5.0 on my current Web API 2.2 project. When I browse to /swagger I can see that the page loads but the call to load /swagger/docs/v1 fail with a 500 error status. Currently, I have the basic config in place without any customizations. 

Here's the generated exception :

```
Exception: System.Web.HttpUnhandledException (0x80004005): Value cannot be null. Parameter name: key ---> System.ArgumentNullException: Value cannot be null. Parameter name: key

at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
at Swashbuckle.Swagger.SchemaRegistry.CreateInlineSchema(Type type, String refPrefix)
at Swashbuckle.Swagger.SchemaRegistry.CreateArraySchema(JsonArrayContract arrayContract, String refPrefix)
at Swashbuckle.Swagger.SchemaRegistry.<>c__DisplayClass1b.<CreateObjectSchema>b__14(JsonProperty prop)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Swashbuckle.Swagger.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract, String refPrefix)
at Swashbuckle.Swagger.SchemaRegistry.GetOrRegister(Type type)
at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry)
at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)
at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
```

**Comment by domaindrivendev** [comment]
Hi there

Looking at that method it's hard to be sure exactly where this is occurring without a little more debug info. If you can spare the time, it would be really helpful if you could pull down and build from source (use built.bat) and debug locally? At a minimum, this would at least give you the exact line number which you could pass on.

Thanks

**Comment by domaindrivendev** [comment]
From the limited stack trace, it looks like maybe CollectionItemType in the following method is returning null.

    // Swashbuckle.Core.Swagger.SchemaRegistry.cs
    private Schema CreateArraySchema(JsonArrayContract arrayContract, string refPrefix)
    {
        return new Schema
            {
                type = "array",
                items = CreateInlineSchema(arrayContract.CollectionItemType, refPrefix)
            };
    }

I've no idea what would cause this (an array without an item type doesn't make much sense) but it would explain the stack trace above. If your debugging could identify the array type (e.g. arrayContract.UnderlyingType) which is causing this, that would be really helpful in getting to the bottom of this.

Thanks

**Comment by latenightcoder** [comment]
Turns out the underlying type is an IEnumerable and I have no way of modifying the type of this property at the moment (3rd party library from Telerik).

**Comment by domaindrivendev** [comment]
Great catch - that should be handled correctly by SB. I'll get a fix out ASAP!

It's worth noting that, without any type information, the best SB can do here is describe it as an array of objects

**Comment by latenightcoder** [comment]
Makes complete sense. Thank you for the quick responses!
