### ISSUE TITLE
Error java.util.NoSuchElementException importing Swagger to SoapUI

### ISSUE THREAD

**Issue by bayani88** [domaindrivendev/Swashbuckle#439]
I'm having issues importing Swagger to SoapUI 5.2.0.  I'm able to partially import the swagger definition, but then this error occurs.  Any thoughts on why this error is occurring or how I can import ?  

Below is a copy of the Error log in SoapUI.  

Thu Jul 23 11:22:24 CDT 2015:ERROR:java.util.NoSuchElementException
   java.util.NoSuchElementException
   	at java.util.Collections$EmptyIterator.next(Unknown Source)
   	at java_util_Iterator$next.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
   	at com.smartbear.swagger.Swagger2Importer$_addOperation_closure3.doCall(Swagger2Importer.groovy:174)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
   	at groovy.lang.Closure.call(Closure.java:411)
   	at groovy.lang.Closure.call(Closure.java:427)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:3875)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1354)
   	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
   	at com.smartbear.swagger.Swagger2Importer.addOperation(Swagger2Importer.groovy:164)
   	at com.smartbear.swagger.Swagger2Importer$addOperation.callCurrent(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
   	at com.smartbear.swagger.Swagger2Importer.importPath(Swagger2Importer.groovy:114)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
   	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
   	at com.smartbear.swagger.Swagger2Importer$_importSwagger_closure1.doCall(Swagger2Importer.groovy:68)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
   	at groovy.lang.Closure.call(Closure.java:411)
   	at groovy.lang.Closure.call(Closure.java:427)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:3875)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1354)
   	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
   	at com.smartbear.swagger.Swagger2Importer.importSwagger(Swagger2Importer.groovy:67)
   	at com.smartbear.swagger.SwaggerImporter$importSwagger.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
   	at com.smartbear.swagger.SwaggerUtils$1.construct(SwaggerUtils.groovy:64)
   	at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:46)
   	at com.eviware.soapui.support.swing.SwingWorker$2.run(SwingWorker.java:131)
   	at java.lang.Thread.run(Unknown Source)

**Comment by bayani88** [comment]
These definitions imported:
/api/product/{id}
/api/product/View

These would not import:
/api/product/{id}/Something
/api/product/{id}/Something/{Type}
/api/product/{id}/Something/{Type}/View

**Comment by domaindrivendev** [comment]
Knowing virtually nothing about the SoapUI tool, I can only hazard a guess that the Swagger document, auto-generated by Swashbuckle is possibly invalid according to the Swagger 2.0 spec.

To confirm if this is the case, could you take the Swagger generated by SB and POST it to the online swagger validator - http://online.swagger.io/validator/debug?

Let me know the results and we can take it from there ...

**Comment by domaindrivendev** [comment]
Closing due to inactivity. Feel free to re-open if you have additional information after trying the validator as described above
