### ISSUE TITLE
ApplyParamComments throws exception when parameter is annotated with [FromUri]

### ISSUE THREAD

**Issue by toddschilling** [domaindrivendev/Swashbuckle#908]
**framework**: netcoreapp1.0
**package-version**: 6.0.0-beta901

**steps to reproduce**:
1. create aspnet.core api using the **Microsoft.AspNetCore.Mvc.WebApiCompatShim**.
2. add a parameter to one of the api methods and attribute it with [**FromUri**].  Set the route accordingly.
3. document the api with xml, including the new parameter.
4. configure swashbuckle to include xml comments.

**notes**:
If you remove the xml comment for the parameter, the swagger ui will show the parameter twice, once as a path&query parameter and another as a required path parameter.  
If you remove the [FromUri] attribute and use [FromRoute] instead, swagger works as intended.

**exception**: 

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Swashbuckle.SwaggerGen.Annotations.XmlCommentsOperationFilter.ApplyParamComments(Operation operation, XPathNavigator methodNode)
   at Swashbuckle.SwaggerGen.Annotations.XmlCommentsOperationFilter.Apply(Operation operation, OperationFilterContext context)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.<>c__DisplayClass4_0.<GetSwagger>b__4(IGrouping`2 group)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.GetSwagger(String apiVersion, String host, String basePath, String[] schemes)
   at Swashbuckle.Swagger.Application.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

```

**Comment by toddschilling** [comment]
The doesn't appear to be related to the name of the parameter.   I'll confirm the root cause and close or update shortly.

**Comment by domaindrivendev** [comment]
There is now a separate project specifically for ASP.NET Core and I believe this issue may be resolved if you use the latest version of that package:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore

Please try it out and let me know. If you're still seeing the same problem, I'd appreciate if you could re-create the issue in that repo. Thanks.
